version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ROOT
      MYSQL_DATABASE: devops
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pROOT"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  flask-app:
    image: manish612/two-tier-flask-app:latest
    container_name: flask-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: ROOT
      MYSQL_DB: devops
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:

